TrajectoryPlannerROS:
 max_vel_x: 3.5
 min_vel_x: 0.5
 escape_vel: -1.0
 max_vel_theta: 2.5
 min_vel_theta: -2.5
 # min_in_place_vel_theta: -2.5

 acc_lim_theta: 3.0
 acc_lim_x: 2.3
 acc_lim_y: 0

 xy_goal_tolerance: 0.20
 yaw_goal_tolerance: 2.00
 latch_xy_goal_tolerance: true

 holonomic_robot: false
 meter_scoring: true

# DWAPlannerROS: 
#   acc_lim_th: 6.0 
#   acc_lim_x: 4.0 
#   acc_lim_y: 0.0

#   max_vel_x: 3.5
#   min_vel_x: -2.5 

#   max_vel_y: 0.0 
#   min_vel_y: 0.0

#   max_vel_theta: 6.0 
#   min_vel_theta: 0.0 

#   max_vel_trans: 3.5
#   min_vel_trans: 1.0
#   # max_vel_rot: 2.0 
#   # min_vel_rot: -2.0 
#   sim_time: 1.7 
#   sim_granularity: 0.025 
#   goal_distance_bias: 32.0 
#   path_distance_bias: 24.0 
#   occdist_scale: 0.01 
#   stop_time_buffer: 0.2 
#   oscillation_reset_dist: 0.05 
#   forward_point_distance: 0.325 
#   scaling_speed: 0.25 
#   max_scaling_factor: 0.2 
#   vx_samples: 3 
#   vy_samples: 0
#   vth_samples: 20 
#   sim_period: 0.1 
#   xy_goal_tolerance: 0.25 
#   yaw_goal_tolerance: 0.10 
  # latch_xy_goal_tolerance: false

