#TrajectoryPlannerROS:
#  max_vel_x: 1.0
#  min_vel_x: 0.5
#  escape_vel: -0.4
#  max_vel_theta: 2.5
#  min_vel_theta: -1.5
#  min_in_place_vel_theta: -0.4

#  acc_lim_theta: 3.0
#  acc_lim_x: 2.3
#  acc_lim_y: 0

#  xy_goal_tolerance: 0.20
#  yaw_goal_tolerance: 0.05

#  holonomic_robot: false
#  dwa: true
#  meter_scoring: true

DWAPlannerROS: 
  acc_lim_th: 4.0 
  acc_lim_x: 4.0 
  acc_lim_y: 0.0

  max_vel_x: 3.5
  min_vel_x: -0.5 

  max_vel_y: 0.0 
  min_vel_y: 0.0

  max_trans_vel: 2.5
  min_trans_vel: 0.8
  max_rot_vel: 2.0 
  min_rot_vel: -2.0 
  sim_time: 1.7 
  sim_granularity: 0.025 
  goal_distance_bias: 32.0 
  path_distance_bias: 24.0 
  occdist_scale: 0.01 
  stop_time_buffer: 0.2 
  oscillation_reset_dist: 0.05 
  forward_point_distance: 0.325 
  scaling_speed: 0.25 
  max_scaling_factor: 0.2 
  vx_samples: 3 
  vy_samples: 0
  vth_samples: 20 
  sim_period: 0.1 
  xy_goal_tolerance: 0.25 
  yaw_goal_tolerance: 0.05 

