obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.7, 0.3], [-0.7, 0.3], [-0.7, -0.3], [0.7, -0.3]]
#robot_radius: 0.4
inflation_radius: 0.55

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: sensor/velodyne_scan, marking: true, clearing: true}


