global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  static_map: true
  rolling_window: false
  track_unknown_space: true

  plugins: 
      - {name: static,    type: "costmap_2d::StaticLayer"}            
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  static:        
      map_topic: /map 
      subscribe_to_updates: true 

inflation_layer:
  inflation_radius: 0.01
  # global_frame: odom
  # robot_base_frame: base_link
  # update_frequency: 5.0
  # publish_frequency: 2.0
  # static_map: false
  # rolling_window: true
  # width: 100.0
  # height: 100.0
  # resolution: 0.05